---
title: "**研究自述**"
author: "劉昱佑"
date: "`r sprintf('%d 年 %d 月', as.integer(format(Sys.Date(), '%Y')) - 1911, as.integer(format(Sys.Date(), '%m')))`"
output:
  pdf_document:
    latex_engine: xelatex
    pandoc_args: ["--lua-filter=bold-me.lua"]
geometry: "margin=1in"
fontsize: 11pt
linestretch: 1.25
bibliography: rs.bib
csl: rs.csl
link-citations: true
linkcolor: blue
urlcolor: blue
mainfont: "texgyrepagella-regular.otf"
mainfontoptions: "Scale=1.0, BoldFont=texgyrepagella-bold.otf, ItalicFont=texgyrepagella-italic.otf, BoldItalicFont=texgyrepagella-bolditalic.otf"
CJKmainfont: "源雲明體月"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{=latex}
{\raggedleft\small[\href{https://yyliou.github.io/yyliou/rs/rs.pdf}{English version}]\par}
```

空氣污染、交通事故與地下水超抽有一個共同點，就是造成損害的人不必承擔其成本，環境與資源經濟學稱之為外部性。政府常以交通規則、工程建設、補貼、土地分區與認證制度加以因應，但這些政策是否有效、又帶來哪些其他影響，是重要的實證議題。我的研究運用因果推論方法與臺灣全國性的行政資料進行評估，結果往往與政策原先的預期不同。外部性不只來自工廠的煙囪，也發生在農田與街道上，因此我的研究分為兩條相互連結的主軸。第一條主軸探討農業的環境友善作法能否同時提高農家所得，第二條主軸則探討交通規則、工程建設、票價與大型活動如何影響道路上的事故與排放。

過去評估這類政策，多仰賴實驗室實驗、模擬分析或小規模調查。我的兩條研究主軸則都結合全國性的行政資料與準實驗設計，直接估計政策對實際結果的影響。

## 一、農業生產與環境

環境友善的作法若會降低農民收入，便難以推廣，因此這條主軸關心環境目標與農家所得能否兼顧。

發展太陽光電需要大量土地，但在農地上設置光電，容易引發與農業爭地的疑慮。屋頂型光電不占用農地，然而過去的證據多來自實驗室研究。研究運用 2020 年農林漁牧業普查資料，發現設置屋頂型光電的畜禽場銷售額較高 [@liou2025rooftop]，其中養雞場增加 5.8%，主要來自產量的提升 [@lee2025solar]。由於屋頂面積有限，政府也劃設漁電共生區域，讓光電板架設於魚塭上方。土地劃入該區域後，農地價格上漲 13.5%，可能反映了開發權利的價值 [@chang2026aquavoltaics]。

除了能源之外，農業對環境更普遍的影響來自化學肥料與農藥，這類污染的來源分散，難以直接管制。食品溯源制度以食品安全為目的，過去的研究也多從消費者的角度探討。研究發現，採行溯源制度的農戶使用化學肥料、農藥與地下水的機率分別下降 8.2、15.4 與 40 個百分點，收入也同時提高 [@chang2026food]。換言之，食品安全政策也帶來了環境效益。

然而，並非所有環境友善的作法都能提高收入。樹種多樣性較高的林農，平均收入雖然較低，收入卻明顯較為穩定，而且波動降低的幅度大於收入減少的幅度 [@lee2025forest]。由此可知，環境友善的作法即使未能提高收入，仍能透過降低風險使農民受益。

## 二、交通、移動與外部性

交通活動所產生的外部性，主要是事故與排放。大眾運輸常被視為同時減少這兩者的方法，因此我先探討哪些因素會改變大眾運輸的使用。COVID-19 期間臺灣並未封城，但每增加一例確診，臺北捷運運量仍下降 1.43%，可見光是對健康風險的感受，就足以改變搭乘行為 [@chang2021metro]。在政策方面，臺北月票使捷運運量增加 4.3% [@liou2025monthly]。不過，唯有新增旅次中有 70% 至 80% 取代汽機車旅次，碳排放才會下降。

由於多數旅次仍仰賴機動車輛，道路安全有賴交通規則與工程設施的配合。臺南市部分行政區取消機車兩段式左轉後，事故數下降 21% [@liou2026hookturn]，可見不符合用路人直覺的規則，反而可能提高事故風險。在工程設施方面，過去的行人保護研究多仰賴虛擬實境模擬。研究評估全國性的路口改善計畫，由於計畫優先改善高風險路口，研究以逆機率加權法處理選擇偏誤。結果顯示受傷事故下降 8.2%，行人事故下降 14.8%，每投入 1 元約可減少 3.5 元的醫療成本 [@liou2027ppi]。

除了日常移動，大型活動也會在短時間內帶來大量車流。客家地區元宵掃墓期間，空氣品質下降 17.5%。過去研究多將節慶污染歸因於燒香、紙錢與鞭炮，但研究發現主要原因是機動車輛的使用增加 [@chang2024air]。大甲媽祖遶境期間，事故數增加 14.9%，連不在遶境路線上的鄰近鄉鎮也增加 9.8% [@liou2026religious]。無論是日常通勤或宗教活動，交通的外部性主要都來自機動車輛。

## 三、其他研究

我也運用相同的方法，分析市場如何因應外部衝擊。疫情期間，消費者依循貝氏模型的預測更新判斷，並將食品消費移轉至線上 [@liou2024covid]。疫情過後，觀光旅館的營收回升來自房價上漲而非住客增加 [@liou2026hotel]。此外，策略性貿易模型也顯示，歐盟的碳邊境調整機制會促使出口廠商投資綠能 [@liou2025cbam]。

無論在農村或都市，我的研究都在探討，當政策或外部衝擊改變了損害環境的代價或改善環境的報酬時，誰會因此改變行為、改變多少，以及成本與效益由誰承擔。

\newpage

## 參考文獻
